;(function(){
	'use strict';

	kmcModule = angular.module('kmcPatientinfoModule',[]);
	kmcModule.config(['$windowProvider', '$stateProvider', '$urlRouterProvider', '$locationProvider','$httpProvider',
		 function($windowProvider, $stateProvider, $urlRouterProvider, $locationProvider,$httpProvider){
		 	$stateProvider
		 	.state('acne',{
		 		url:'/patient-information/acne',
		 		templateUrl:'app/modules/key-info/patient-info/acne.html'
		 	})
		 	.state('antibiotics',{
		 		url:'/patient-information/antibiotics',
		 		templateUrl:'app/modules/key-info/patient-info/antibiotics.html'
		 	})
		 	.state('arthritis',{
		 		url:'/patient-information/arthritis',
		 		templateUrl:'app/modules/key-info/patient-info/arthritis.html'
		 	})
		 	.state('backache',{
		 		url:'/patient-information/backache',
		 		templateUrl:'app/modules/key-info/patient-info/backache.html'
		 	})
		 	.state('benign-prostatic-hypertrophy',{
		 		url:'/patient-information/benign-prostatic-hypertrophy',
		 		templateUrl:'app/modules/key-info/patient-info/benign-prostatic-hypertrophy.html'
		 	})
		 	.state('cervical-smear',{
		 		url:'/patient-information/baccervical-smearkache',
		 		templateUrl:'app/modules/key-info/patient-info/cervical-smear.html'
		 	})
		 	.state('cold--flu',{
		 		url:'/patient-information/baccold--flukache',
		 		templateUrl:'app/modules/key-info/patient-info/cold--flu.html'
		 	})
		 	.state('copd',{
		 		url:'/patient-information/copd',
		 		templateUrl:'app/modules/key-info/patient-info/copd.html'
		 	})
			 .state('depression',{
		 		url:'/patient-information/depression',
		 		templateUrl:'app/modules/key-info/patient-info/depression.html'
		 	})
			 .state('eczema',{
		 		url:'/patient-information/eczema',
		 		templateUrl:'app/modules/key-info/patient-info/eczema.html'
		 	})
			  .state('epilepsy',{
		 		url:'/patient-information/epilepsy',
		 		templateUrl:'app/modules/key-info/patient-info/epilepsy.html'
		 	})
			 .state('fever',{
		 		url:'/patient-information/fever',
		 		templateUrl:'app/modules/key-info/patient-info/fever.html'
		 	})
			  .state('headache',{
		 		url:'/patient-information/headache',
		 		templateUrl:'app/modules/key-info/patient-info/headache.html'
		 	})
			  .state('irritable-bowel-syndrome',{
		 		url:'/patient-information/irritable-bowel-syndrome',
		 		templateUrl:'app/modules/key-info/patient-info/irritable-bowel-syndrome.html'
		 	})
			.state('insomnia',{
		 		url:'/patient-information/insomnia',
		 		templateUrl:'app/modules/key-info/patient-info/insomnia.html'
		 	})
			.state('menopause',{
		 		url:'/patient-information/menopause',
		 		templateUrl:'app/modules/key-info/patient-info/menopause.html'
		 	})
			.state('reflux-oesophagitis',{
		 		url:'/patient-information/reflux-oesophagitis',
		 		templateUrl:'app/modules/key-info/patient-info/reflux-oesophagitis.html'
		 	})
			 .state('shingles',{
		 		url:'/patient-information/shingles',
		 		templateUrl:'app/modules/key-info/patient-info/shingles.html'
		 	})
			.state('sore-throat',{
		 		url:'/patient-information/sore-throat',
		 		templateUrl:'app/modules/key-info/patient-info/sore-throat.html'
		 	})
			.state('vaginal-thrush',{
		 		url:'/patient-information/vaginal-thrush',
		 		templateUrl:'app/modules/key-info/patient-info/vaginal-thrush.html'
		 	});
	}]);
})();
